version: '3'

services:
  wattpilot:
    image: ghcr.io/joscha82/wattpilot:main
    command: server
    restart: always
    environment:
      - HA_ENABLED=${HA_ENABLED:-true}
      - MQTT_ENABLED=${MQTT_ENABLED:-true}
      - MQTT_HOST=${MQTT_HOST:-}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_PUBLISH_MESSAGES=${MQTT_PUBLISH_MESSAGES:-false}
      - MQTT_PUBLISH_PROPERTIES=${MQTT_PUBLISH_PROPERTIES:-true}
      - WATTPILOT_LOGLEVEL=${WATTPILOT_LOGLEVEL:-INFO}
      - WATTPILOT_HOST=${WATTPILOT_HOST:-}
      - WATTPILOT_PASSWORD=${WATTPILOT_PASSWORD:-}
